(defun lesser (n x)    
    (if (null x)
        nil
        (if (<= n (car x))
            (lesser n (cdr x))
            (cons (car x) (lesser n (cdr x)))
        )
    )
)
(defun greater (n x)
    (if (null x)
        nil
        (if (> n (car x)) 
            (greater n (cdr x))
            (cons (car x) (greater n (cdr x)))
        )
    )
)
(defun pivot (n x)
    (if (null x)
        (list '() '())
        (list(lesser n x) (greater n x))
    )
)
(defun quicksort (xs)
    (if (null xs)
        nil
        (append 
          (quicksort (car (pivot (car xs) (cdr xs)))) 
          (list (car xs)) 
          (quicksort (car(cdr (pivot (car xs) (cdr xs))))) 
        )
    )
)