(defun reachable (transition start final input)
    (cond ((equal input nil)
           (cond ((equal start final) t) (t nil))
          )
          ((reachall transition (funcall transition start (car input)) final input))
    )
)
(defun reachall (transition start final input)
    (cond 
        ((null final) nil)
        ((null start) nil)
        ((null input) t) 
        ((eql(reachable transition (car start) final (cdr input)) t)t)
        ((reachall transition (cdr start) final input))
    )
)